/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

/**
 *
 * @author light
 */
public class BookEntry extends javax.swing.JFrame {

    /**
     * Creates new form BookEntry
     */
    public BookEntry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtAuthor = new app.bolivia.swing.JCTextField();
        txtTitle = new app.bolivia.swing.JCTextField();
        txtEdition = new app.bolivia.swing.JCTextField();
        txtPlaceOfPublication = new app.bolivia.swing.JCTextField();
        txtPublisher = new app.bolivia.swing.JCTextField();
        txtYearOfPublication = new app.bolivia.swing.JCTextField();
        txtNumberOfPages = new app.bolivia.swing.JCTextField();
        txtSeries = new app.bolivia.swing.JCTextField();
        txtISBN = new app.bolivia.swing.JCTextField();
        txtQuantity = new app.bolivia.swing.JCTextField();
        jLabel2 = new javax.swing.JLabel();
        rSButtonHover3 = new rojeru_san.complementos.RSButtonHover();
        jPanel4 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(860, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAuthor.setBackground(new java.awt.Color(255, 255, 255));
        txtAuthor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(99, 166, 211)));
        txtAuthor.setForeground(new java.awt.Color(102, 102, 102));
        txtAuthor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAuthor.setPlaceholder("Author");
        txtAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorActionPerformed(evt);
            }
        });
        jPanel2.add(txtAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 290, 30));

        txtTitle.setBackground(new java.awt.Color(255, 255, 255));
        txtTitle.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(99, 166, 211)));
        txtTitle.setForeground(new java.awt.Color(102, 102, 102));
        txtTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTitle.setPlaceholder("Ttitle");
        txtTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTitleFocusLost(evt);
            }
        });
        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });
        jPanel2.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 290, 30));

        txtEdition.setBackground(new java.awt.Color(255, 255, 255));
        txtEdition.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(99, 166, 211)));
        txtEdition.setForeground(new java.awt.Color(102, 102, 102));
        txtEdition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEdition.setPlaceholder("Edition");
        txtEdition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditionActionPerformed(evt);
            }
        });
        jPanel2.add(txtEdition, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 290, 30));

        txtPlaceOfPublication.setBackground(new java.awt.Color(255, 255, 255));
        txtPlaceOfPublication.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(99, 166, 211)));
        txtPlaceOfPublication.setForeground(new java.awt.Color(102, 102, 102));
        txtPlaceOfPublication.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPlaceOfPublication.setPlaceholder("Place of publication");
        txtPlaceOfPublication.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPlaceOfPublicationFocusLost(evt);
            }
        });
        txtPlaceOfPublication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlaceOfPublicationActionPerformed(evt);
            }
        });
        jPanel2.add(txtPlaceOfPublication, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 290, 30));

        txtPublisher.setBackground(new java.awt.Color(255, 255, 255));
        txtPublisher.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(99, 166, 211)));
        txtPublisher.setForeground(new java.awt.Color(102, 102, 102));
        txtPublisher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPublisher.setPlaceholder("Publisher");
        txtPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPublisherActionPerformed(evt);
            }
        });
        jPanel2.add(txtPublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 290, 30));

        txtYearOfPublication.setBackground(new java.awt.Color(255, 255, 255));
        txtYearOfPublication.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(99, 166, 211)));
        txtYearOfPublication.setForeground(new java.awt.Color(102, 102, 102));
        txtYearOfPublication.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtYearOfPublication.setPlaceholder("Year of publication");
        txtYearOfPublication.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtYearOfPublicationFocusLost(evt);
            }
        });
        txtYearOfPublication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearOfPublicationActionPerformed(evt);
            }
        });
        jPanel2.add(txtYearOfPublication, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 290, 30));

        txtNumberOfPages.setBackground(new java.awt.Color(255, 255, 255));
        txtNumberOfPages.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(99, 166, 211)));
        txtNumberOfPages.setForeground(new java.awt.Color(102, 102, 102));
        txtNumberOfPages.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumberOfPages.setPlaceholder("Number of pages");
        txtNumberOfPages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberOfPagesActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumberOfPages, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 290, 30));

        txtSeries.setBackground(new java.awt.Color(255, 255, 255));
        txtSeries.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(99, 166, 211)));
        txtSeries.setForeground(new java.awt.Color(102, 102, 102));
        txtSeries.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSeries.setPlaceholder("Series");
        txtSeries.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSeriesFocusLost(evt);
            }
        });
        txtSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeriesActionPerformed(evt);
            }
        });
        jPanel2.add(txtSeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 290, 30));

        txtISBN.setBackground(new java.awt.Color(255, 255, 255));
        txtISBN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(99, 166, 211)));
        txtISBN.setForeground(new java.awt.Color(102, 102, 102));
        txtISBN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtISBN.setPlaceholder("ISBN");
        txtISBN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtISBNFocusLost(evt);
            }
        });
        txtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISBNActionPerformed(evt);
            }
        });
        jPanel2.add(txtISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 290, 30));

        txtQuantity.setBackground(new java.awt.Color(255, 255, 255));
        txtQuantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(99, 166, 211)));
        txtQuantity.setForeground(new java.awt.Color(102, 102, 102));
        txtQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtQuantity.setPlaceholder("Quantity");
        txtQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantityFocusLost(evt);
            }
        });
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        jPanel2.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 290, 30));

        jLabel2.setText("Please Enter the books information");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        rSButtonHover3.setBackground(new java.awt.Color(99, 166, 211));
        rSButtonHover3.setText("Add");
        rSButtonHover3.setColorHover(new java.awt.Color(51, 153, 255));
        rSButtonHover3.setColorTextHover(new java.awt.Color(204, 204, 204));
        rSButtonHover3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover3ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonHover3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 160, 30));

        jPanel4.setBackground(new java.awt.Color(175, 193, 231));
        jPanel4.setForeground(new java.awt.Color(255, 0, 51));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Back to Home");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 240, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorActionPerformed

    private void txtTitleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTitleFocusLost

    }//GEN-LAST:event_txtTitleFocusLost

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    private void txtEditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditionActionPerformed

    private void txtPlaceOfPublicationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlaceOfPublicationFocusLost

    }//GEN-LAST:event_txtPlaceOfPublicationFocusLost

    private void txtPlaceOfPublicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlaceOfPublicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlaceOfPublicationActionPerformed

    private void txtPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPublisherActionPerformed

    private void txtYearOfPublicationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtYearOfPublicationFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearOfPublicationFocusLost

    private void txtYearOfPublicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearOfPublicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearOfPublicationActionPerformed

    private void txtNumberOfPagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberOfPagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberOfPagesActionPerformed

    private void txtQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityFocusLost

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void txtSeriesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSeriesFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeriesFocusLost

    private void txtSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeriesActionPerformed

    private void txtISBNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtISBNFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISBNFocusLost

    private void txtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISBNActionPerformed

    private void rSButtonHover3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover3ActionPerformed

    }//GEN-LAST:event_rSButtonHover3ActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        HomePage homePage=new HomePage();
        homePage.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private rojeru_san.complementos.RSButtonHover rSButtonHover3;
    private app.bolivia.swing.JCTextField txtAuthor;
    private app.bolivia.swing.JCTextField txtEdition;
    private app.bolivia.swing.JCTextField txtISBN;
    private app.bolivia.swing.JCTextField txtNumberOfPages;
    private app.bolivia.swing.JCTextField txtPlaceOfPublication;
    private app.bolivia.swing.JCTextField txtPublisher;
    private app.bolivia.swing.JCTextField txtQuantity;
    private app.bolivia.swing.JCTextField txtSeries;
    private app.bolivia.swing.JCTextField txtTitle;
    private app.bolivia.swing.JCTextField txtYearOfPublication;
    // End of variables declaration//GEN-END:variables
}
