package JFrame;
import java.awt.Color;
import java.sql.*;
import javax.swing.*;
public class HomePage extends javax.swing.JFrame {

    
    Color mouseEnterColor=new Color(99,166,211);
    Color mouseExitColor=new Color(175,193,231);
    
    
    public HomePage() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        adminHomePagePanel = new javax.swing.JPanel();
        libraryStatusPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        adminMenuPanel = new javax.swing.JPanel();
        bookEntryPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        registeredStudentsPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        returnBooksPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        issueBooksPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        aboutUsPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        bookCataloguePanel = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        viewIssuedBooksPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(240, 247, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminHomePagePanel.setBackground(new java.awt.Color(240, 247, 255));
        adminHomePagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        libraryStatusPanel.setBackground(new java.awt.Color(240, 247, 255));
        libraryStatusPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Books Quantity");
        libraryStatusPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Registered Student");
        libraryStatusPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Issued Book");
        libraryStatusPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel17.setBackground(new java.awt.Color(102, 102, 102));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("10");
        libraryStatusPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel18.setBackground(new java.awt.Color(102, 102, 102));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("10");
        libraryStatusPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));

        jLabel19.setBackground(new java.awt.Color(102, 102, 102));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("10");
        libraryStatusPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        adminHomePagePanel.add(libraryStatusPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 810, 40));

        adminMenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        adminMenuPanel.setMaximumSize(new java.awt.Dimension(0, 0));
        adminMenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookEntryPanel.setBackground(new java.awt.Color(175, 193, 231));
        bookEntryPanel.setForeground(new java.awt.Color(255, 0, 51));
        bookEntryPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookEntryPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookEntryPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookEntryPanelMouseExited(evt);
            }
        });
        bookEntryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Book Entry");
        bookEntryPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        adminMenuPanel.add(bookEntryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 240, 40));

        registeredStudentsPanel.setBackground(new java.awt.Color(175, 193, 231));
        registeredStudentsPanel.setForeground(new java.awt.Color(255, 0, 51));
        registeredStudentsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Registered Students");
        registeredStudentsPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        adminMenuPanel.add(registeredStudentsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 240, 40));

        returnBooksPanel.setBackground(new java.awt.Color(175, 193, 231));
        returnBooksPanel.setForeground(new java.awt.Color(255, 0, 51));
        returnBooksPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Return Books");
        returnBooksPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        adminMenuPanel.add(returnBooksPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 240, 40));

        issueBooksPanel.setBackground(new java.awt.Color(175, 193, 231));
        issueBooksPanel.setForeground(new java.awt.Color(255, 0, 51));
        issueBooksPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issueBooksPanelMouseClicked(evt);
            }
        });
        issueBooksPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Issue Books");
        issueBooksPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        adminMenuPanel.add(issueBooksPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 240, 40));

        logoutPanel.setBackground(new java.awt.Color(255, 51, 51));
        logoutPanel.setForeground(new java.awt.Color(0, 0, 0));
        logoutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("LOGOUT");
        logoutPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        adminMenuPanel.add(logoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 120, 40));

        aboutUsPanel.setBackground(new java.awt.Color(99, 166, 211));
        aboutUsPanel.setForeground(new java.awt.Color(255, 0, 51));
        aboutUsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("About Us");
        aboutUsPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        adminMenuPanel.add(aboutUsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 120, 40));

        bookCataloguePanel.setBackground(new java.awt.Color(175, 193, 231));
        bookCataloguePanel.setForeground(new java.awt.Color(255, 0, 51));
        bookCataloguePanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bookCataloguePanelFocusGained(evt);
            }
        });
        bookCataloguePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookCataloguePanelMouseClicked(evt);
            }
        });
        bookCataloguePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Book Catalogue");
        bookCataloguePanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        adminMenuPanel.add(bookCataloguePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 240, 40));

        viewIssuedBooksPanel.setBackground(new java.awt.Color(175, 193, 231));
        viewIssuedBooksPanel.setForeground(new java.awt.Color(255, 0, 51));
        viewIssuedBooksPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("View Issued books");
        viewIssuedBooksPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        adminMenuPanel.add(viewIssuedBooksPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 240, 40));

        adminHomePagePanel.add(adminMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 810, 410));

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Runtime");
        adminHomePagePanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Error");
        adminHomePagePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(99, 166, 211));
        jLabel3.setText("Library Managemnet System");
        adminHomePagePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 50));

        jPanel2.add(adminHomePagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 590));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 590));

        setSize(new java.awt.Dimension(867, 596));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bookEntryPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookEntryPanelMouseClicked
        BookEntry bookEntry=new BookEntry();
        bookEntry.setVisible(true);
        dispose();
    }//GEN-LAST:event_bookEntryPanelMouseClicked

    private void bookCataloguePanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookCataloguePanelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_bookCataloguePanelFocusGained

    private void bookCataloguePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookCataloguePanelMouseClicked
        BookCatalogue bookCatalogue=new BookCatalogue();
        bookCatalogue.setVisible(true);
        dispose();
    }//GEN-LAST:event_bookCataloguePanelMouseClicked

    private void bookEntryPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookEntryPanelMouseEntered
        bookEntryPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_bookEntryPanelMouseEntered

    private void bookEntryPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookEntryPanelMouseExited
         bookEntryPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_bookEntryPanelMouseExited

    private void issueBooksPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBooksPanelMouseClicked
        IssueBook issueBook=new IssueBook();
        issueBook.setVisible(true);
        dispose();
    }//GEN-LAST:event_issueBooksPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutUsPanel;
    private javax.swing.JPanel adminHomePagePanel;
    private javax.swing.JPanel adminMenuPanel;
    private javax.swing.JPanel bookCataloguePanel;
    private javax.swing.JPanel bookEntryPanel;
    private javax.swing.JPanel issueBooksPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel libraryStatusPanel;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JPanel registeredStudentsPanel;
    private javax.swing.JPanel returnBooksPanel;
    private javax.swing.JPanel viewIssuedBooksPanel;
    // End of variables declaration//GEN-END:variables
}
