package JFrame;
import java.sql.*;
import javax.swing.*;
public class StudentLoginPage extends javax.swing.JFrame{
    
      public String studentID;
      private String password;

    
    public StudentLoginPage() {
        
        initComponents();
       
    }
 
    //validation
    public boolean validationLogin(){
        studentID=txtStudentID.getText();
        password=txtStudentPassword.getText();
        
        if(studentID.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter your ID");
            return false;
        }
        if(password.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter password");
            return false;
        }
        return true;
    }
    
    //credential verification
    public void login(){
        studentID=txtStudentID.getText();
        password=txtStudentPassword.getText();
        
        try{
            Connection connection = DatabaseConnectionClass.getConnection();
            PreparedStatement statement= connection.prepareStatement("select * from students where studentID=? and password=?");
            
            statement.setString(1,studentID);
            statement.setString(2, password);
            
            ResultSet resultSet= statement.executeQuery();
            
            if(resultSet.next()){
                JOptionPane.showMessageDialog(this, "Login Successful");
                HomePage homePage= new HomePage();
                homePage.setVisible(true);
                
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this, "Incorrect studentID or passowrd");
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
  
    }
    
    public String getID(){
        
        String v="kala jahangir";
        
        return v;
    }


   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        studentLoginIcon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtStudentID = new app.bolivia.swing.JCTextField();
        txtStudentPassword = new app.bolivia.swing.JCTextField();
        studentLoginButton = new rojeru_san.complementos.RSButtonHover();
        jLabel7 = new javax.swing.JLabel();
        studentSignupButton = new rojeru_san.complementos.RSButtonHover();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(99, 166, 211));
        jLabel3.setText("Library Managemnet System");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        studentLoginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/login.library-concept-students-coworking-space-vector-27466179.jpg"))); // NOI18N
        studentLoginIcon.setText("jLabel5");
        jPanel2.add(studentLoginIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 490, 600));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Don't have an account?");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 210, 30));

        txtStudentID.setBackground(new java.awt.Color(255, 255, 255));
        txtStudentID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(99, 166, 211)));
        txtStudentID.setForeground(new java.awt.Color(102, 102, 102));
        txtStudentID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStudentID.setPlaceholder("Student ID");
        txtStudentID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStudentIDFocusLost(evt);
            }
        });
        txtStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIDActionPerformed(evt);
            }
        });
        jPanel2.add(txtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 290, -1));

        txtStudentPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtStudentPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(99, 166, 211)));
        txtStudentPassword.setForeground(new java.awt.Color(102, 102, 102));
        txtStudentPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStudentPassword.setPlaceholder("Password");
        txtStudentPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtStudentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 290, -1));

        studentLoginButton.setBackground(new java.awt.Color(99, 166, 211));
        studentLoginButton.setText("LOGIN");
        studentLoginButton.setColorHover(new java.awt.Color(51, 153, 255));
        studentLoginButton.setColorTextHover(new java.awt.Color(204, 204, 204));
        studentLoginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentLoginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(studentLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 160, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Please insert your LOGIN information");
        jLabel7.setFocusable(false);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 340, 30));

        studentSignupButton.setBackground(new java.awt.Color(99, 166, 211));
        studentSignupButton.setText("SIGNUP");
        studentSignupButton.setColorHover(new java.awt.Color(51, 153, 255));
        studentSignupButton.setColorTextHover(new java.awt.Color(204, 204, 204));
        studentSignupButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentSignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSignupButtonActionPerformed(evt);
            }
        });
        jPanel2.add(studentSignupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 160, 30));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Error");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Runtime");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 600));

        setSize(new java.awt.Dimension(871, 602));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIDActionPerformed

    private void studentLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentLoginButtonActionPerformed
        if(validationLogin()){
            login();
           System.out.println(getID()); 
        }
        
    }//GEN-LAST:event_studentLoginButtonActionPerformed

    private void studentSignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSignupButtonActionPerformed
         AdminSignUpPage signupPage=new AdminSignUpPage();
         signupPage.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_studentSignupButtonActionPerformed

    private void txtStudentIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStudentIDFocusLost
     
    }//GEN-LAST:event_txtStudentIDFocusLost

    private void txtStudentPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLoginPage().setVisible(true);
                StudentLoginPage sLoginPage=new StudentLoginPage();
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private rojeru_san.complementos.RSButtonHover studentLoginButton;
    private javax.swing.JLabel studentLoginIcon;
    private rojeru_san.complementos.RSButtonHover studentSignupButton;
    public app.bolivia.swing.JCTextField txtStudentID;
    private app.bolivia.swing.JCTextField txtStudentPassword;
    // End of variables declaration//GEN-END:variables
}
